# .gitpod.yml
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Android Setup
    init: |
      # Install dependencies
      sudo apt update && sudo apt install -y qemu-kvm libvirt-clients libvirt-daemon-system bridge-utils virt-manager
      sudo chmod 777 /dev/kvm
      sudo usermod -aG kvm gitpod
    command: |
      echo "Android environment ready!"
